name: Github 3D Profile Contributions

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Github 3D Profile
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name emreyunusbas
          git config user.email emrebasyunus1@gmail.com
          git add -A .
          git commit -m "Generate & Update 3D Profile"
          git push
