name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */8 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate Snake Game Contributions
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        - name: Commit & Push
        run: |
          git config user.name emreyunusbas
          git config user.email emrebasyunus1@gmail.com
          git add -A .
          git commit -m "Generate & Update 3D Profile"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
