name: Generate Snake

on:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate Snake Game Contributions
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile-3d-contrib/snake-game/github-contribution-grid-snake.svg
            profile-3d-contrib/snake-game/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push SVG files to the repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          directory: profile-3d-contrib
          branch: main
