name: Generate Snake

on:
  schedule:
    # Her 6 saatte bir çalışır
    - cron: "0 */8 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate Snake Game Contributions
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: emreyunusbas
          outputs: |
            Recursive-Power/eco/github-contribution-grid-snake.svg
            Recursive-Power/eco/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: Recursive-Power/eco
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
