name: Generate Snake

on:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate Snake Game Contributions
        uses: aelassas/snk/svg-only@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DIR: emreyunusbas/emreyunusbas/snakegame
          outputs: |
            snakegame/github-contribution-grid-snake.svg
            snakegame/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push changes
        run: |
          git config user.name "emreyunusbas"
          git config user.email "emrebasyunus1@gmail.com"
          git add .
          git commit -m "Add Snake Game contributions"
          git push origin main

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          branch: main
          folder: emreyunusbas/emreyunusbas/profile-3d-contrib/snakegame
